// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDomains(arg1:string,arg2:number,arg3:number,arg4:number):Promise<void>;

export function GetDeveloper():Promise<string>;

export function GetVersion():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function SaveCSVDialog(arg1:string):Promise<void>;

export function StopCheck():Promise<void>;
