// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDomains(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CheckDomains'](arg1, arg2, arg3, arg4);
}

export function GetDeveloper() {
  return window['go']['main']['App']['GetDeveloper']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function SaveCSVDialog(arg1) {
  return window['go']['main']['App']['SaveCSVDialog'](arg1);
}

export function StopCheck() {
  return window['go']['main']['App']['StopCheck']();
}
